# Generated by Django 4.2.6 on 2023-10-31 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='project_desc',
            field=models.TextField(default='None'),
        ),
        migrations.AddField(
            model_name='projects',
            name='project_is_ml',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projects',
            name='project_is_web',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projects',
            name='project_link',
            field=models.URLField(default='None'),
        ),
        migrations.AddField(
            model_name='projects',
            name='project_team',
            field=models.CharField(default='Kishan Kumar,', max_length=100),
        ),
    ]
