# Generated by Django 4.2.6 on 2023-10-31 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_soft_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('company', models.CharField(default=None, max_length=30)),
                ('is_end_date', models.BooleanField()),
                ('start_date', models.DateField(default=None)),
                ('end_date', models.DateField(default=None)),
                ('desc', models.TextField()),
            ],
        ),
    ]
