# Generated by Django 4.2.6 on 2023-10-31 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_experience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='is_end_date',
        ),
    ]
