# Generated by Django 4.2.6 on 2023-11-01 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_rename_shool_education_school'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='project_is_ml',
            new_name='is_ml',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='project_is_web',
            new_name='is_web',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='id',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='id',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='project_desc',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='project_link',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='project_name',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='project_team',
        ),
        migrations.AddField(
            model_name='profile',
            name='instagram',
            field=models.URLField(default=None),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin',
            field=models.URLField(default=None),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter',
            field=models.URLField(default=None),
        ),
        migrations.AddField(
            model_name='projects',
            name='desc',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='projects',
            name='link',
            field=models.URLField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='name',
            field=models.CharField(default=None, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.BigIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='profile',
            name='summary',
            field=models.TextField(default=None),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.profile')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.projects')),
            ],
        ),
    ]
