# Generated by Django 4.2.6 on 2023-11-01 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_profile_instagram_alter_profile_twitter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='instagram',
            new_name='insta',
        ),
    ]
