# Generated by Django 4.2.6 on 2023-11-01 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_rename_instagram_profile_insta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='insta',
            new_name='instagram',
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='linkedin',
            field=models.URLField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.BigIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='summary',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='desc',
            field=models.TextField(default=None, null=True),
        ),
    ]
