# Generated by Django 4.2.6 on 2023-11-01 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_rename_insta_profile_instagram_alter_profile_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='member_id',
        ),
        migrations.RemoveField(
            model_name='team',
            name='project_id',
        ),
    ]
