# Generated by Django 4.2.6 on 2023-11-01 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_remove_team_member_id_remove_team_project_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='member_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.profile'),
        ),
        migrations.AddField(
            model_name='team',
            name='project_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.projects'),
        ),
    ]
