# Generated by Django 4.2.6 on 2023-11-01 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_profile_address_alter_profile_dob_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('project_id', 'member_id')},
        ),
    ]
