# Generated by Django 4.2.6 on 2023-11-01 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_team_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='bio',
            field=models.CharField(default='Nothing', max_length=30),
        ),
    ]
